### ISSUE TITLE
memoryshare-win32-ia32-msvc has no .node file

### ISSUE THREAD

**Issue by hwen** [zhangyuang/sharedMemory#2]
Hi, I test with window and install with ia32 Electron app, but found that memoryshare-win32-ia32-msvc has no .node file

**Comment by zhangyuang** [comment]
fix by 1.0.6

**Comment by hwen** [comment]
seen not publish success，the new version is 1.0.4
https://www.npmjs.com/package/memoryshare?activeTab=versions

**Comment by zhangyuang** [comment]
This optionalDependencies has been published, reinstall it with delete lock file

**Comment by hwen** [comment]
ok~
