### ISSUE TITLE
Feature request: Set base path

### ISSUE THREAD

**Issue by hwen** [zhangyuang/sharedMemory#4]
`init` will create a file in current run folder.

When bundle an Electron app that `init` will crash and fail to create file (test in window). Also have a problem in mac, cause installed app have no permission to create file in program folder, app can only create/write file in usersData, logs, caches folder.

So it is better that we can set the base path to usersData folder instead of creating file in program folder.

**Comment by zhangyuang** [comment]
The memId parameter can be an absolute path

**Comment by hwen** [comment]
got it
